name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Yarn Setup
      # You may pin to the exact commit or the version.
      # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
      uses: DerYeger/yarn-setup-action@v1.0.1
      with:
        # The version of Node.js that will be used
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
      run: | 
        yarn install
        yarn build
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "autodeploy@metaos.im"
        git config --global user.name "autodeploy"
        cd docs/dist
        git init
        git add -A
        git commit -m 'auto deploy'
        git push -f git@git.github.com:metaos-labs/docs.git master:gh-pages
        
